apiVersion: apps/v1
kind: Deployment
metadata:
  name: divvy
  labels:
    app: divvy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: divvy
  template:
    metadata:
      labels:
        app: divvy
    spec:
      containers:
      - name: divvy
        image: divvy:latest
        ports:
        - containerPort: 80