apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: thedivvy-app-staging
  namespace: default
spec:
  secretName: thedivvy-app-tls-staging
  issuerRef:
    kind: ClusterIssuer
    # The cluster issuer created previously
    name: letsencrypt-staging
  commonName: thedivvy.app
  dnsNames:
  - thedivvy.app
  - www.thedivvy.app
  acme:
    config:
    - dns01:
        # The provider in the previously created issuer
        provider: clouddns-provider-staging
      domains:
      - thedivvy.app
      - www.thedivvy.app
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: thedivvy-app-prod
  namespace: default
spec:
  secretName: thedivvy-app-tls-prod
  issuerRef:
    kind: ClusterIssuer
    # The cluster issuer created previously
    name: letsencrypt-prod
  commonName: thedivvy.app
  dnsNames:
  - thedivvy.app
  - www.thedivvy.app
  acme:
    config:
    - dns01:
        # The provider in the previously created issuer
        provider: clouddns-provider-prod
      domains:
      - thedivvy.app
      - www.thedivvy.app
