# Generated by Django 2.2 on 2019-04-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='available_zones',
            field=models.ManyToManyField(blank=True, to='users.Zone'),
        ),
    ]
