# Generated by Django 2.2 on 2019-04-24 19:28

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.validators.is_hostname_supported], verbose_name='email address'),
        ),
    ]
