# Generated by Django 2.2 on 2019-04-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='fqdn',
            new_name='hostname',
        ),
    ]
