# Generated by Django 2.2 on 2019-04-25 20:28

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190424_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_minor',
            field=models.BooleanField(validators=[users.validators.validate_value_is_False]),
        ),
    ]
