# Generated by Django 2.2 on 2019-04-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
