# Generated by Django 2.2 on 2019-04-25 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='passenger_capacity',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
            preserve_default=False,
        ),
    ]
