# Generated by Django 2.2 on 2019-05-15 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
