# Generated by Django 2.2 on 2019-04-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=100)),
                ('scheduled_departure_time', models.DateTimeField()),
                ('scheduled_arrival_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('details',),
            },
        ),
    ]
