# Generated by Django 2.2 on 2019-04-23 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comment_thread', '0001_initial'),
        ('zone_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=100)),
                ('scheduled_departure_time', models.DateTimeField()),
                ('scheduled_arrival_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True)),
                ('comments', models.ManyToManyField(to='comment_thread.Comment')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zone_management.Zone')),
            ],
            options={
                'ordering': ('details',),
            },
        ),
    ]
