# Generated by Django 2.2 on 2019-05-07 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(blank=True, max_length=100)),
                ('scheduled_departure_time', models.DateTimeField()),
                ('scheduled_arrival_time', models.DateTimeField()),
                ('actual_departure_time', models.DateTimeField(blank=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ('details',),
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('vehicle_plate_confirmed', models.BooleanField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_calendar.Journey')),
            ],
        ),
    ]
