# Generated by Django 2.2 on 2019-04-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_calendar', '0002_auto_20190423_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journey',
            name='passengers',
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('vehicle_plate_confirmed', models.BooleanField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_calendar.Journey')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
