# Generated by Django 2.2 on 2019-04-28 18:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_calendar', '0003_auto_20190428_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='passengers',
            field=models.ManyToManyField(related_name='trip_calendar_journey_related', through='trip_calendar.Passenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
