# Generated by Django 2.2 on 2019-04-21 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calendar', '0003_auto_20190421_0127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trip_calendar.Vehicle'),
        ),
    ]
