# Generated by Django 2.2 on 2019-05-08 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zone_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_calendar', '0003_auto_20190508_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desired_departure_time', models.DateTimeField()),
                ('allowed_genders', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('desired_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='zone_management.Zone')),
                ('desired_pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_calendar_request_related', to='zone_management.Zone')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
