# Generated by Django 2.2 on 2019-04-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calendar', '0004_auto_20190421_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='journey',
        ),
        migrations.AddField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='journey',
            name='comments',
            field=models.ManyToManyField(to='trip_calendar.Comment'),
        ),
    ]
