# Generated by Django 2.2 on 2019-05-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calendar', '0004_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='allowed_genders',
            new_name='allowed_gender',
        ),
        migrations.AddField(
            model_name='journey',
            name='allowed_gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
