# Generated by Django 2.2 on 2019-04-22 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_calendar', '0005_auto_20190421_0339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='member',
            new_name='author',
        ),
    ]
