# Generated by Django 2.2 on 2019-05-08 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip_calendar', '0005_auto_20190508_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='picked_up_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, related_name='trip_calendar_request_related', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
