# Generated by Django 2.2 on 2019-05-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0002_contact_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email address'),
        ),
    ]
