# Generated by Django 2.2 on 2019-05-15 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0003_auto_20190514_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
