# Generated by Django 2.2 on 2019-05-15 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact_management', '0004_contact_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
