# Generated by Django 2.2 on 2019-04-23 09:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_known_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
