# Generated by Django 2.2 on 2019-04-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_tracker', '0003_tracker_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
